// ============================================================================
// KIN SENTINEL AUTHORIZATION PLANE
// Rigorous execution barrier enforcing fail-closed capabilities,
// destructive/irreversible action gates, secret resolution, and audit logging.
// ============================================================================

import { AutonomyMode, RiskLevel } from '../domain/types.js';
import { PolicyEngine, ActionEvaluationRequest, PolicyEvaluationResult } from '../policy/policy_engine.js';
import { SecretBroker } from './secret_broker.js';
import { EventLedger } from './event_ledger.js';
import * as crypto from 'node:crypto';

function canonicalJson(obj: any): string {
  if (obj === null || typeof obj !== 'object') {
    return JSON.stringify(obj);
  }
  if (Array.isArray(obj)) {
    return '[' + obj.map(canonicalJson).join(',') + ']';
  }
  const keys = Object.keys(obj).sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + canonicalJson(obj[k])).join(',') + '}';
}

export interface SentinelCheckRequest {
  agentId: string;
  runId?: string;
  parentRunId?: string;
  toolName: string;
  params: Record<string, any>;
  riskLevel: RiskLevel;
  autonomyMode: AutonomyMode;
  agentCapabilities: string[];
  authorizationToken?: string;
}

export interface SentinelDecision {
  allowed: boolean;
  requiresApproval: boolean;
  reason: string;
  isDestructive: boolean;
  sanitizedParams: Record<string, any>;
}

export class Sentinel {
  private static instance: Sentinel;
  private policyEngine: PolicyEngine;
  private secretBroker: SecretBroker;
  private validApprovalTokens: Map<string, { toolName: string; runId?: string; paramDigest?: string; expiresAt: number }> = new Map();

  private constructor() {
    this.policyEngine = new PolicyEngine();
    this.secretBroker = SecretBroker.getInstance();
  }

  public static getInstance(): Sentinel {
    if (!Sentinel.instance) {
      Sentinel.instance = new Sentinel();
    }
    return Sentinel.instance;
  }

  public getPolicyEngine(): PolicyEngine {
    return this.policyEngine;
  }

  public computeApprovalDigest(toolName: string, runId?: string, params?: Record<string, any>): string {
    const canonical = params ? canonicalJson(params) : '';
    return crypto
      .createHash('sha256')
      .update(`${toolName}:${runId || '*'}:${canonical}`)
      .digest('hex');
  }

  public hasApprovalToken(token: string): boolean {
    const entry = this.validApprovalTokens.get(token);
    if (!entry) return false;
    if (Date.now() > entry.expiresAt) {
      this.validApprovalTokens.delete(token);
      return false;
    }
    return true;
  }

  /**
   * Registers a single-use authorization token generated by operator approval.
   */
  public registerApprovalToken(
    token: string,
    toolName: string,
    ttlMs: number = 300000,
    runId?: string,
    paramsOrDigest?: Record<string, any> | string
  ): void {
    let paramDigest: string | undefined;
    if (typeof paramsOrDigest === 'string') {
      paramDigest = paramsOrDigest;
    } else if (paramsOrDigest && typeof paramsOrDigest === 'object') {
      paramDigest = this.computeApprovalDigest(toolName, runId, paramsOrDigest);
    }

    this.validApprovalTokens.set(token, {
      toolName,
      runId,
      paramDigest,
      expiresAt: Date.now() + ttlMs,
    });
  }

  /**
   * Consumes a single-use authorization token.
   */
  public consumeApprovalToken(
    token: string,
    toolName: string,
    runId?: string,
    paramsOrDigest?: Record<string, any> | string
  ): boolean {
    const entry = this.validApprovalTokens.get(token);
    if (!entry) return false;

    if (Date.now() > entry.expiresAt) {
      this.validApprovalTokens.delete(token);
      return false;
    }

    if (entry.toolName !== toolName && entry.toolName !== '*') {
      return false;
    }

    if (entry.runId && runId && entry.runId !== '*' && entry.runId !== runId) {
      return false;
    }

    if (entry.paramDigest) {
      let candidateDigest: string | undefined;
      if (typeof paramsOrDigest === 'string') {
        candidateDigest = paramsOrDigest;
      } else if (paramsOrDigest && typeof paramsOrDigest === 'object') {
        candidateDigest = this.computeApprovalDigest(toolName, entry.runId || '*', paramsOrDigest);
      }
      if (!candidateDigest || candidateDigest !== entry.paramDigest) {
        return false;
      }
    }

    this.validApprovalTokens.delete(token);
    return true;
  }

  public getRequiredCapability(toolName: string): { primary: string; aliases: string[] } {
    if (toolName.startsWith('mcp__')) {
      return { primary: 'mcp:call', aliases: ['mcp:call', 'mcp', toolName, '*'] };
    }

    if (toolName.startsWith('skill__')) {
      return { primary: 'skills:manage', aliases: ['skills:manage', 'skills', 'skill', toolName, '*'] };
    }

    switch (toolName) {
      case 'create_skill':
      case 'createSkill':
      case 'import_skill':
      case 'importSkill':
      case 'execute_skill':
      case 'executeSkill':
        return { primary: 'skills:manage', aliases: ['skills:manage', 'skills', 'skill', 'agent:coordinate', 'create_skill', 'createSkill', 'import_skill', 'importSkill', 'execute_skill', 'executeSkill', '*'] };

      case 'readFile':
      case 'listDirectory':
        return { primary: 'fs:read', aliases: ['fs:read', 'fs_read', 'read', 'fs'] };
      case 'writeFile':
        return { primary: 'fs:write', aliases: ['fs:write', 'fs_write', 'write', 'fs'] };
      case 'executeShell':
      case 'shell':
        return { primary: 'shell:exec', aliases: ['shell:exec', 'shell', 'exec'] };
      case 'browser':
      case 'browserNavigate':
      case 'browserClick':
      case 'browserType':
      case 'browserInspect':
      case 'browserScreenshot':
      case 'browserEvaluate':
      case 'browserStep':
      case 'browserClose':
        return { primary: 'web:browse', aliases: ['web:browse', 'web', 'browser', 'web_browse'] };
      case 'computer':
      case 'application':
      case 'desktopScreenshot':
      case 'desktopDiscoverApps':
      case 'desktopLaunchApp':
      case 'desktopListWindows':
      case 'desktopFocusWindow':
      case 'desktopCloseWindow':
      case 'desktopMouseMove':
      case 'desktopMouseClick':
      case 'desktopType':
      case 'desktopSendKey':
        return { primary: 'gui:desktop', aliases: ['gui:desktop', 'gui', 'desktop', 'computer', 'gui_desktop'] };
      case 'schedule':
      case 'cancelSchedule':
      case 'listSchedules':
        return { primary: 'schedule:cron', aliases: ['schedule:cron', 'schedule', 'cron'] };
      case 'delegateToAgent':
      case 'proposePlanAdjustment':
        return { primary: 'agent:delegate', aliases: ['agent:delegate', 'delegate', 'agent', 'proposePlanAdjustment', '*'] };
      default:
        return { primary: 'fs:read', aliases: ['fs:read', 'fs_read', 'read', 'fs'] };
    }
  }

  /**
   * Authoritative check for non-reversible or destructive operations.
   */
  public isDestructiveAction(toolName: string, params: Record<string, any>): { isDestructive: boolean; reason?: string } {
    const lowerTool = toolName.toLowerCase();

    // 1. Explicit destructive tool names
    if (
      lowerTool.includes('delete') ||
      lowerTool.includes('removefile') ||
      lowerTool.includes('droptable') ||
      lowerTool.includes('truncatedata') ||
      lowerTool.includes('purgedatabase')
    ) {
      return {
        isDestructive: true,
        reason: `Tool '${toolName}' is an inherently destructive file/database operation.`,
      };
    }

    // 2. Destructive shell commands
    if (lowerTool === 'executeshell' || lowerTool === 'shell') {
      const cmd = (params?.command || '').toLowerCase();
      const destructivePatterns = [
        /\brm\s+(-[a-z]*r[a-z]*f|-[a-z]*f[a-z]*r)/i, // rm -rf, rm -fr
        /\brm\s+-r\s+/i,
        /\bdel(\.exe)?\s+\/[a-z]*f/i, // del /f
        /\brmdir\s+\/s/i, // rmdir /s
        /\bformat\s+[a-z]:/i, // format C:
        /\bgit\s+reset\s+--hard\b/i, // git reset --hard
        /\bgit\s+clean\s+-[a-z]*f/i, // git clean -fd
        /\bdrop\s+(table|database|schema)\b/i, // DROP TABLE
        /\btruncate\s+(table)?\b/i, // TRUNCATE TABLE
        /\bmkfs\b/i, // mkfs
        /\bdd\s+if=/i, // dd if=
      ];

      for (const pattern of destructivePatterns) {
        if (pattern.test(cmd)) {
          return {
            isDestructive: true,
            reason: `Shell command contains a destructive/non-reversible pattern: "${params?.command}"`,
          };
        }
      }
    }

    return { isDestructive: false };
  }

  /**
   * Authoritative gateway evaluation before tool execution.
   */
  public evaluate(request: SentinelCheckRequest): SentinelDecision {
    // 1. Fail-closed capability verification
    if (!request.agentCapabilities || request.agentCapabilities.length === 0) {
      return {
        allowed: false,
        requiresApproval: false,
        reason: `SECURITY DENIAL: Fail-closed capability check. Agent '${request.agentId}' holds zero allowed capabilities.`,
        isDestructive: false,
        sanitizedParams: request.params,
      };
    }

    if (!request.agentCapabilities.includes('*')) {
      const capInfo = this.getRequiredCapability(request.toolName);
      const hasCap = request.agentCapabilities.some((cap) => {
        const norm = cap.trim().toLowerCase();
        return norm === '*' || norm === request.toolName.toLowerCase() || capInfo.aliases.includes(norm);
      });
      if (!hasCap) {
        return {
          allowed: false,
          requiresApproval: false,
          reason: `SECURITY DENIAL: FORBIDDEN: Agent '${request.agentId}' lacks required capability '${capInfo.primary}' for tool '${request.toolName}'. Allowed: [${request.agentCapabilities.join(', ')}]`,
          isDestructive: false,
          sanitizedParams: request.params,
        };
      }
    }

    // 2. Destructive action detection (Mandatory Operator Approval)
    const destructive = this.isDestructiveAction(request.toolName, request.params);

    // 3. Single-use approval token verification (bypasses re-prompting once operator approves)
    if (request.authorizationToken) {
      const authorized = this.consumeApprovalToken(request.authorizationToken, request.toolName, request.runId, request.params);
      if (authorized) {
        // Resolve vault placeholders for authorized execution
        const resolvedParams = this.secretBroker.resolvePlaceholders(request.params);
        return {
          allowed: true,
          requiresApproval: false,
          reason: `Action pre-authorized via consumed single-use operator approval token.`,
          isDestructive: destructive.isDestructive,
          sanitizedParams: resolvedParams,
        };
      }
    }

    // If action is destructive, enforce interactive approval regardless of autonomy mode
    if (destructive.isDestructive) {
      return {
        allowed: true,
        requiresApproval: true,
        reason: destructive.reason || `Non-reversible or destructive operation requires explicit operator approval.`,
        isDestructive: true,
        sanitizedParams: request.params,
      };
    }

    // 4. PolicyEngine evaluation for standard capability attenuation and autonomy rules
    const commandOrPath = request.params?.filePath || request.params?.path || request.params?.command || request.params?.dirPath;
    const policyReq: ActionEvaluationRequest = {
      agentId: request.agentId,
      parentRunId: request.parentRunId,
      toolName: request.toolName,
      commandOrPath,
      riskLevel: request.riskLevel,
      autonomyMode: request.autonomyMode,
      agentCapabilities: request.agentCapabilities,
    };

    const policyResult: PolicyEvaluationResult = this.policyEngine.evaluateAction(policyReq);

    if (!policyResult.allowed) {
      return {
        allowed: false,
        requiresApproval: false,
        reason: policyResult.reason,
        isDestructive: false,
        sanitizedParams: request.params,
      };
    }

    if (policyResult.requiresInteractiveApproval) {
      return {
        allowed: true,
        requiresApproval: true,
        reason: policyResult.reason,
        isDestructive: false,
        sanitizedParams: request.params,
      };
    }

    // 5. Authorized for direct execution: resolve vault placeholders
    const resolvedParams = this.secretBroker.resolvePlaceholders(request.params);
    return {
      allowed: true,
      requiresApproval: false,
      reason: policyResult.reason,
      isDestructive: false,
      sanitizedParams: resolvedParams,
    };
  }

  /**
   * Sanitizes output results before returning them to the model or persisting in action records.
   */
  public sanitizeObservation(output: string): string {
    return this.secretBroker.redactSecrets(output);
  }
}
